<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Solarium\\' => array($vendorDir . '/solarium/solarium/library'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
);
